### ISSUE TITLE
Internal link?

### ISSUE THREAD

**Issue by Thatoo** [nextcloud/picker#37]
Could it be possible to add to the list of choices ("Display only" and "Modify"), the internal link?
![image](https://github.com/nextcloud/picker/assets/464782/d22f19d8-b259-40cf-9db1-64116e780317)

I open this smaller feature request as a small step towards https://github.com/nextcloud/picker/issues/34

**Comment by Thatoo** [comment]
I've made a PR for that https://github.com/nextcloud/picker/pull/38

**Comment by provokateurin** [comment]
https://github.com/nextcloud/picker/pull/47
