### ISSUE TITLE
NextcloudVue 8 and Nextcloud-dialog 5.3.2?

### ISSUE THREAD

**Issue by Thatoo** [nextcloud/picker#40]
Any plan to move Picker to more recent version of NextcloudVue and Nextcloud-dialog?

**Comment by provokateurin** [comment]
Yes that will happen eventually, but there is no timeline at the moment. Feel free to open a PR if you can.

**Comment by Thatoo** [comment]
I wish I could. I'm not sure I'm knowledgeable enough for this task.

**Comment by Thatoo** [comment]
> Yes that will happen eventually, but there is no timeline at the moment. Feel free to open a PR if you can.

I started modestly to try to move toward nextcloud-dialogs v4.2.0 https://github.com/nextcloud/picker/pull/42
It displays the picker window but doesn't yet list files and directory. I don't understand why.

**Comment by provokateurin** [comment]
https://github.com/nextcloud/picker/pull/47
